# Generated by Django 5.0.6 on 2024-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("hub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.TextField(max_length="20")),
            ],
        ),
        migrations.AlterField(
            model_name="custom_user",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="customuser_set", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="custom_user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="customuser_set", to="auth.permission"
            ),
        ),
    ]
